-- Grant permissions to kmbruce user for all tables
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO kmbruce;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO kmbruce;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON TABLES TO kmbruce;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON SEQUENCES TO kmbruce;


